package com.rozsa.network;

import java.util.HashMap;

public enum MessageType {
    UNKNOWN(-1),
    CONNECTION_REQUEST(1),
    CONNECTION_RESPONSE(2),
    CONNECTION_ESTABLISHED(3),
    CONNECTION_DENIED(4),
    CONNECTION_CLOSED(5),
    PING(6),
    PONG(7),
    ACK(8),
    UNRELIABLE(9),
    RELIABLE(10),
    INTERNAL(11),

    UNRELIABLE_SEQUENCED_00(32, 32),
    UNRELIABLE_SEQUENCED_01(32, 33),
    UNRELIABLE_SEQUENCED_02(32, 34),
    UNRELIABLE_SEQUENCED_03(32, 35),
    UNRELIABLE_SEQUENCED_04(32, 36),
    UNRELIABLE_SEQUENCED_05(32, 37),
    UNRELIABLE_SEQUENCED_06(32, 38),
    UNRELIABLE_SEQUENCED_07(32, 39),
    UNRELIABLE_SEQUENCED_08(32, 40),
    UNRELIABLE_SEQUENCED_09(32, 41),
    UNRELIABLE_SEQUENCED_10(32, 42),
    UNRELIABLE_SEQUENCED_11(32, 43),
    UNRELIABLE_SEQUENCED_12(32, 44),
    UNRELIABLE_SEQUENCED_13(32, 45),
    UNRELIABLE_SEQUENCED_14(32, 46),
    UNRELIABLE_SEQUENCED_15(32, 47),
    UNRELIABLE_SEQUENCED_16(32, 48),
    UNRELIABLE_SEQUENCED_17(32, 49),
    UNRELIABLE_SEQUENCED_18(32, 50),
    UNRELIABLE_SEQUENCED_19(32, 51),
    UNRELIABLE_SEQUENCED_20(32, 52),
    UNRELIABLE_SEQUENCED_21(32, 53),
    UNRELIABLE_SEQUENCED_22(32, 54),
    UNRELIABLE_SEQUENCED_23(32, 55),
    UNRELIABLE_SEQUENCED_24(32, 56),
    UNRELIABLE_SEQUENCED_25(32, 57),
    UNRELIABLE_SEQUENCED_26(32, 58),
    UNRELIABLE_SEQUENCED_27(32, 59),
    UNRELIABLE_SEQUENCED_28(32, 60),
    UNRELIABLE_SEQUENCED_29(32, 61),
    UNRELIABLE_SEQUENCED_30(32, 62),
    UNRELIABLE_SEQUENCED_31(32, 63),

    RELIABLE_SEQUENCED_00(64, 64),
    RELIABLE_SEQUENCED_01(64, 65),
    RELIABLE_SEQUENCED_02(64, 66),
    RELIABLE_SEQUENCED_03(64, 67),
    RELIABLE_SEQUENCED_04(64, 68),
    RELIABLE_SEQUENCED_05(64, 69),
    RELIABLE_SEQUENCED_06(64, 70),
    RELIABLE_SEQUENCED_07(64, 71),
    RELIABLE_SEQUENCED_08(64, 72),
    RELIABLE_SEQUENCED_09(64, 73),
    RELIABLE_SEQUENCED_10(64, 74),
    RELIABLE_SEQUENCED_11(64, 75),
    RELIABLE_SEQUENCED_12(64, 76),
    RELIABLE_SEQUENCED_13(64, 77),
    RELIABLE_SEQUENCED_14(64, 78),
    RELIABLE_SEQUENCED_15(64, 79),
    RELIABLE_SEQUENCED_16(64, 80),
    RELIABLE_SEQUENCED_17(64, 81),
    RELIABLE_SEQUENCED_18(64, 82),
    RELIABLE_SEQUENCED_19(64, 83),
    RELIABLE_SEQUENCED_20(64, 84),
    RELIABLE_SEQUENCED_21(64, 85),
    RELIABLE_SEQUENCED_22(64, 86),
    RELIABLE_SEQUENCED_23(64, 87),
    RELIABLE_SEQUENCED_24(64, 88),
    RELIABLE_SEQUENCED_25(64, 89),
    RELIABLE_SEQUENCED_26(64, 90),
    RELIABLE_SEQUENCED_27(64, 91),
    RELIABLE_SEQUENCED_28(64, 92),
    RELIABLE_SEQUENCED_29(64, 93),
    RELIABLE_SEQUENCED_30(64, 94),
    RELIABLE_SEQUENCED_31(64, 95),

    RELIABLE_ORDERED_00(96, 96),
    RELIABLE_ORDERED_01(96, 97),
    RELIABLE_ORDERED_02(96, 98),
    RELIABLE_ORDERED_03(96, 99),
    RELIABLE_ORDERED_04(96, 100),
    RELIABLE_ORDERED_05(96, 101),
    RELIABLE_ORDERED_06(96, 102),
    RELIABLE_ORDERED_07(96, 103),
    RELIABLE_ORDERED_08(96, 104),
    RELIABLE_ORDERED_09(96, 105),
    RELIABLE_ORDERED_10(96, 106),
    RELIABLE_ORDERED_11(96, 107),
    RELIABLE_ORDERED_12(96, 108),
    RELIABLE_ORDERED_13(96, 109),
    RELIABLE_ORDERED_14(96, 110),
    RELIABLE_ORDERED_15(96, 111),
    RELIABLE_ORDERED_16(96, 112),
    RELIABLE_ORDERED_17(96, 113),
    RELIABLE_ORDERED_18(96, 114),
    RELIABLE_ORDERED_19(96, 115),
    RELIABLE_ORDERED_20(96, 116),
    RELIABLE_ORDERED_21(96, 117),
    RELIABLE_ORDERED_22(96, 118),
    RELIABLE_ORDERED_23(96, 119),
    RELIABLE_ORDERED_24(96, 120),
    RELIABLE_ORDERED_25(96, 121),
    RELIABLE_ORDERED_26(96, 122),
    RELIABLE_ORDERED_27(96, 123),
    RELIABLE_ORDERED_28(96, 124),
    RELIABLE_ORDERED_29(96, 125),
    RELIABLE_ORDERED_30(96, 126),
    RELIABLE_ORDERED_31(96, 127),

    ;

    private final byte baseId;
    private final byte id;

    MessageType(int id) {
        this.id = (byte)id;
        this.baseId = (byte)id;
    }

    MessageType(int baseId, int id) {
        this.baseId = (byte)baseId;
        this.id = (byte)id;
    }

    byte getId() {
        return id;
    }

    public byte getBaseId() {
        return baseId;
    }

    public int getOffset() {
        return id - baseId;
    }

    private static HashMap<Byte, MessageType> idToTypeMapper;

    static {
        idToTypeMapper = new HashMap<>();
        idToTypeMapper.put(UNKNOWN.getId(), UNKNOWN);
        idToTypeMapper.put(CONNECTION_REQUEST.getId(), CONNECTION_REQUEST);
        idToTypeMapper.put(CONNECTION_RESPONSE.getId(), CONNECTION_RESPONSE);
        idToTypeMapper.put(CONNECTION_ESTABLISHED.getId(), CONNECTION_ESTABLISHED);
        idToTypeMapper.put(CONNECTION_DENIED.getId(), CONNECTION_DENIED);
        idToTypeMapper.put(CONNECTION_CLOSED.getId(), CONNECTION_CLOSED);
        idToTypeMapper.put(PING.getId(), PING);
        idToTypeMapper.put(PONG.getId(), PONG);
        idToTypeMapper.put(ACK.getId(), ACK);
        idToTypeMapper.put(UNRELIABLE.getId(), UNRELIABLE);
        idToTypeMapper.put(RELIABLE.getId(), RELIABLE);
        idToTypeMapper.put(INTERNAL.getId(), INTERNAL);

        idToTypeMapper.put(UNRELIABLE_SEQUENCED_00.getId(), UNRELIABLE_SEQUENCED_00);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_01.getId(), UNRELIABLE_SEQUENCED_01);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_02.getId(), UNRELIABLE_SEQUENCED_02);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_03.getId(), UNRELIABLE_SEQUENCED_03);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_04.getId(), UNRELIABLE_SEQUENCED_04);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_05.getId(), UNRELIABLE_SEQUENCED_05);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_06.getId(), UNRELIABLE_SEQUENCED_06);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_07.getId(), UNRELIABLE_SEQUENCED_07);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_08.getId(), UNRELIABLE_SEQUENCED_08);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_09.getId(), UNRELIABLE_SEQUENCED_09);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_10.getId(), UNRELIABLE_SEQUENCED_10);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_11.getId(), UNRELIABLE_SEQUENCED_11);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_12.getId(), UNRELIABLE_SEQUENCED_12);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_13.getId(), UNRELIABLE_SEQUENCED_13);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_14.getId(), UNRELIABLE_SEQUENCED_14);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_15.getId(), UNRELIABLE_SEQUENCED_15);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_16.getId(), UNRELIABLE_SEQUENCED_16);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_17.getId(), UNRELIABLE_SEQUENCED_17);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_18.getId(), UNRELIABLE_SEQUENCED_18);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_19.getId(), UNRELIABLE_SEQUENCED_19);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_20.getId(), UNRELIABLE_SEQUENCED_20);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_21.getId(), UNRELIABLE_SEQUENCED_21);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_22.getId(), UNRELIABLE_SEQUENCED_22);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_23.getId(), UNRELIABLE_SEQUENCED_23);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_24.getId(), UNRELIABLE_SEQUENCED_24);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_25.getId(), UNRELIABLE_SEQUENCED_25);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_26.getId(), UNRELIABLE_SEQUENCED_26);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_27.getId(), UNRELIABLE_SEQUENCED_27);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_28.getId(), UNRELIABLE_SEQUENCED_28);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_29.getId(), UNRELIABLE_SEQUENCED_29);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_30.getId(), UNRELIABLE_SEQUENCED_30);
        idToTypeMapper.put(UNRELIABLE_SEQUENCED_31.getId(), UNRELIABLE_SEQUENCED_31);

        idToTypeMapper.put(RELIABLE_SEQUENCED_00.getId(), RELIABLE_SEQUENCED_00);
        idToTypeMapper.put(RELIABLE_SEQUENCED_01.getId(), RELIABLE_SEQUENCED_01);
        idToTypeMapper.put(RELIABLE_SEQUENCED_02.getId(), RELIABLE_SEQUENCED_02);
        idToTypeMapper.put(RELIABLE_SEQUENCED_03.getId(), RELIABLE_SEQUENCED_03);
        idToTypeMapper.put(RELIABLE_SEQUENCED_04.getId(), RELIABLE_SEQUENCED_04);
        idToTypeMapper.put(RELIABLE_SEQUENCED_05.getId(), RELIABLE_SEQUENCED_05);
        idToTypeMapper.put(RELIABLE_SEQUENCED_06.getId(), RELIABLE_SEQUENCED_06);
        idToTypeMapper.put(RELIABLE_SEQUENCED_07.getId(), RELIABLE_SEQUENCED_07);
        idToTypeMapper.put(RELIABLE_SEQUENCED_08.getId(), RELIABLE_SEQUENCED_08);
        idToTypeMapper.put(RELIABLE_SEQUENCED_09.getId(), RELIABLE_SEQUENCED_09);
        idToTypeMapper.put(RELIABLE_SEQUENCED_10.getId(), RELIABLE_SEQUENCED_10);
        idToTypeMapper.put(RELIABLE_SEQUENCED_11.getId(), RELIABLE_SEQUENCED_11);
        idToTypeMapper.put(RELIABLE_SEQUENCED_12.getId(), RELIABLE_SEQUENCED_12);
        idToTypeMapper.put(RELIABLE_SEQUENCED_13.getId(), RELIABLE_SEQUENCED_13);
        idToTypeMapper.put(RELIABLE_SEQUENCED_14.getId(), RELIABLE_SEQUENCED_14);
        idToTypeMapper.put(RELIABLE_SEQUENCED_15.getId(), RELIABLE_SEQUENCED_15);
        idToTypeMapper.put(RELIABLE_SEQUENCED_16.getId(), RELIABLE_SEQUENCED_16);
        idToTypeMapper.put(RELIABLE_SEQUENCED_17.getId(), RELIABLE_SEQUENCED_17);
        idToTypeMapper.put(RELIABLE_SEQUENCED_18.getId(), RELIABLE_SEQUENCED_18);
        idToTypeMapper.put(RELIABLE_SEQUENCED_19.getId(), RELIABLE_SEQUENCED_19);
        idToTypeMapper.put(RELIABLE_SEQUENCED_20.getId(), RELIABLE_SEQUENCED_20);
        idToTypeMapper.put(RELIABLE_SEQUENCED_21.getId(), RELIABLE_SEQUENCED_21);
        idToTypeMapper.put(RELIABLE_SEQUENCED_22.getId(), RELIABLE_SEQUENCED_22);
        idToTypeMapper.put(RELIABLE_SEQUENCED_23.getId(), RELIABLE_SEQUENCED_23);
        idToTypeMapper.put(RELIABLE_SEQUENCED_24.getId(), RELIABLE_SEQUENCED_24);
        idToTypeMapper.put(RELIABLE_SEQUENCED_25.getId(), RELIABLE_SEQUENCED_25);
        idToTypeMapper.put(RELIABLE_SEQUENCED_26.getId(), RELIABLE_SEQUENCED_26);
        idToTypeMapper.put(RELIABLE_SEQUENCED_27.getId(), RELIABLE_SEQUENCED_27);
        idToTypeMapper.put(RELIABLE_SEQUENCED_28.getId(), RELIABLE_SEQUENCED_28);
        idToTypeMapper.put(RELIABLE_SEQUENCED_29.getId(), RELIABLE_SEQUENCED_29);
        idToTypeMapper.put(RELIABLE_SEQUENCED_30.getId(), RELIABLE_SEQUENCED_30);
        idToTypeMapper.put(RELIABLE_SEQUENCED_31.getId(), RELIABLE_SEQUENCED_31);

        idToTypeMapper.put(RELIABLE_ORDERED_00.getId(), RELIABLE_ORDERED_00);
        idToTypeMapper.put(RELIABLE_ORDERED_01.getId(), RELIABLE_ORDERED_01);
        idToTypeMapper.put(RELIABLE_ORDERED_02.getId(), RELIABLE_ORDERED_02);
        idToTypeMapper.put(RELIABLE_ORDERED_03.getId(), RELIABLE_ORDERED_03);
        idToTypeMapper.put(RELIABLE_ORDERED_04.getId(), RELIABLE_ORDERED_04);
        idToTypeMapper.put(RELIABLE_ORDERED_05.getId(), RELIABLE_ORDERED_05);
        idToTypeMapper.put(RELIABLE_ORDERED_06.getId(), RELIABLE_ORDERED_06);
        idToTypeMapper.put(RELIABLE_ORDERED_07.getId(), RELIABLE_ORDERED_07);
        idToTypeMapper.put(RELIABLE_ORDERED_08.getId(), RELIABLE_ORDERED_08);
        idToTypeMapper.put(RELIABLE_ORDERED_09.getId(), RELIABLE_ORDERED_09);
        idToTypeMapper.put(RELIABLE_ORDERED_10.getId(), RELIABLE_ORDERED_10);
        idToTypeMapper.put(RELIABLE_ORDERED_11.getId(), RELIABLE_ORDERED_11);
        idToTypeMapper.put(RELIABLE_ORDERED_12.getId(), RELIABLE_ORDERED_12);
        idToTypeMapper.put(RELIABLE_ORDERED_13.getId(), RELIABLE_ORDERED_13);
        idToTypeMapper.put(RELIABLE_ORDERED_14.getId(), RELIABLE_ORDERED_14);
        idToTypeMapper.put(RELIABLE_ORDERED_15.getId(), RELIABLE_ORDERED_15);
        idToTypeMapper.put(RELIABLE_ORDERED_16.getId(), RELIABLE_ORDERED_16);
        idToTypeMapper.put(RELIABLE_ORDERED_17.getId(), RELIABLE_ORDERED_17);
        idToTypeMapper.put(RELIABLE_ORDERED_18.getId(), RELIABLE_ORDERED_18);
        idToTypeMapper.put(RELIABLE_ORDERED_19.getId(), RELIABLE_ORDERED_19);
        idToTypeMapper.put(RELIABLE_ORDERED_20.getId(), RELIABLE_ORDERED_20);
        idToTypeMapper.put(RELIABLE_ORDERED_21.getId(), RELIABLE_ORDERED_21);
        idToTypeMapper.put(RELIABLE_ORDERED_22.getId(), RELIABLE_ORDERED_22);
        idToTypeMapper.put(RELIABLE_ORDERED_23.getId(), RELIABLE_ORDERED_23);
        idToTypeMapper.put(RELIABLE_ORDERED_24.getId(), RELIABLE_ORDERED_24);
        idToTypeMapper.put(RELIABLE_ORDERED_25.getId(), RELIABLE_ORDERED_25);
        idToTypeMapper.put(RELIABLE_ORDERED_26.getId(), RELIABLE_ORDERED_26);
        idToTypeMapper.put(RELIABLE_ORDERED_27.getId(), RELIABLE_ORDERED_27);
        idToTypeMapper.put(RELIABLE_ORDERED_28.getId(), RELIABLE_ORDERED_28);
        idToTypeMapper.put(RELIABLE_ORDERED_29.getId(), RELIABLE_ORDERED_29);
        idToTypeMapper.put(RELIABLE_ORDERED_30.getId(), RELIABLE_ORDERED_30);
        idToTypeMapper.put(RELIABLE_ORDERED_31.getId(), RELIABLE_ORDERED_31);
    }

    static MessageType from(byte id) {
        if (!idToTypeMapper.containsKey(id)) {
            return UNKNOWN;
        }

        return idToTypeMapper.get(id);
    }
}
